# Generated by Django 2.1.1 on 2019-02-03 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coaches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Gender', models.CharField(max_length=20)),
                ('Age', models.IntegerField(default=100)),
                ('select_coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.Coaches')),
            ],
        ),
        migrations.CreateModel(
            name='Portions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upper', models.CharField(choices=[('upper', 'upper'), ('lower', 'lower'), ('middle', 'middle'), ('side', 'side')], max_length=2)),
                ('lower', models.CharField(choices=[('upper', 'upper'), ('lower', 'lower'), ('middle', 'middle'), ('side', 'side')], max_length=2)),
                ('middle', models.CharField(choices=[('upper', 'upper'), ('lower', 'lower'), ('middle', 'middle'), ('side', 'side')], max_length=2)),
                ('side', models.CharField(choices=[('upper', 'upper'), ('lower', 'lower'), ('middle', 'middle'), ('side', 'side')], max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='coaches',
            name='S1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S1', to='bookingapp.Portions'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='S2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S2', to='bookingapp.Portions'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='S3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S3', to='bookingapp.Portions'),
        ),
        migrations.AddField(
            model_name='coaches',
            name='S4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='S4', to='bookingapp.Portions'),
        ),
    ]
