# Generated by Django 2.1.1 on 2019-02-03 13:45

import bookingapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_auto_20190203_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='confmd_tkts',
            field=models.IntegerField(default=24, editable=False, verbose_name=bookingapp.models.Coaches),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='rac_tickets',
            field=models.PositiveIntegerField(default=3, verbose_name=bookingapp.models.Coaches),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='waiting_list',
            field=models.PositiveIntegerField(default=5, verbose_name=bookingapp.models.Coaches),
        ),
    ]
